# .travis.yml
#
# https://docs.travis-ci.com/user/languages/r/

language: r
sudo: false
warnings_are_errors: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages: 
  - covr
  - data.table
  - ellipse
  - ggplot2
  - klaR
  - MASS
  - mda
  - mgcv
  - mlbench
  - MLmetrics
  - ModelMetrics
  - nnet
  - pamr
  - party
  - pls
  - proxy
  - randomForest
  - RANN
  - rARPACK
  - reshape2
  - spls
  - subselect
  - superpc
  - testthat
  - xgboost

env:
  global:
  - MAKEFLAGS="-j 2"

r_binary_packages: 
  - NMF
  - RANN
  - fastICA
  - RcppRoll
  - Matrix
  - ipred
  - recipes


before_install:
  - cd pkg/caret
 
after_success:
  - Rscript -e 'covr::codecov()'
