language: r
warnings_are_errors: false
sudo: required

env:
   global:
     - CRAN: http://cran.rstudio.com
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

apt_packages:
  - texlive-base
  - biblatex
  - texlive-latex-base
  - texlive-latex-recommended
  - texlive-latex-extra
  - texlive-fonts-recommended
  - texlive-fonts-extra
  - texlive-science

r_packages:
  - arm
  - glmnet
  - rpart
  - bayesglm
  - C5

r_github_packages:
  - jimhester/covr

before_install:
  - cd pkg/caret
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get -qq update

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library(covr);coveralls()'
