# .travis.yml
#
# https://docs.travis-ci.com/user/languages/r/

language: r
sudo: false
warnings_are_errors: false

r:
  - release

r_packages: 
  - covr
  - data.table
  - DMwR
  - ellipse
  - ggplot2
  - klaR
  - MASS
  - mda
  - mgcv
  - mlbench
  - MLmetrics
  - ModelMetrics
  - nnet
  - pamr
  - party
  - pls
  - proxy
  - randomForest
  - RANN
  - rARPACK
  - reshape2
  - ROSE
  - spls
  - subselect
  - superpc
  - testthat
  - xgboost
 
after_success:
  - Rscript -e 'covr::codecov()'
