# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c
sudo: required

env:
   global:
     - WARNINGS_ARE_ERRORS=1
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX="1"
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_install:
  - cd pkg/caret
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get -qq update
  - ./travis-tool.sh aptget_install texlive-base
  - ./travis-tool.sh aptget_install biblatex
  - ./travis-tool.sh aptget_install texlive-latex-base
  - ./travis-tool.sh aptget_install texlive-latex-recommended
  - ./travis-tool.sh aptget_install texlive-latex-extra
  - ./travis-tool.sh aptget_install texlive-fonts-recommended
  - ./travis-tool.sh aptget_install texlive-fonts-extra
  - ./travis-tool.sh aptget_install texlive-science
  - ./travis-tool.sh github_package jimhester/covr
  - Rscript -e "install.packages('arm')"
  - Rscript -e "install.packages('glmnet')"
  - Rscript -e "install.packages('rpart')"
  - Rscript -e "install.packages('C50')"
  - Rscript -e "install.packages('ipred')"
  - Rscript -e "install.packages('plyr')"
  - Rscript -e "install.packages('earth')"
  - Rscript -e "install.packages('kknn')"
  - Rscript -e 'devtools::install_deps(dep = TRUE)'

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr);coveralls()'
