# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
# http://docs.travis-ci.com/user/languages/r/

language: r
sudo: required
warnings_are_errors: true

env:
   global:
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_install:
  - cd pkg/caret

r_packages:
 - ROSE
 - DMwR

after_success:
  - Rscript -e 'library(covr);coveralls()'
