# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
# http://docs.travis-ci.com/user/languages/r/

language: r
sudo: required
warnings_are_errors: true
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

env:
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_install:
  - cd pkg/caret

r_packages:
 - ROSE
 - DMwR

after_success:
  - Rscript -e 'library(covr);coveralls()'
