# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
# http://docs.travis-ci.com/user/languages/r/

language: r
sudo: required
warnings_are_errors: true

env:
   global:
     - R_BUILD_ARGS="--no-vignettes"
     - R_CHECK_ARGS="--as-cran --no-vignettes"
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_install:
  - cd pkg/caret
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get -qq update

apt_packages:
  - texlive-base
  - biblatex
  - texlive-latex-base
  - texlive-latex-recommended
  - texlive-latex-extra
  - texlive-fonts-recommended
  - texlive-fonts-extra
  - texlive-science

r_packages:
 - ROSE
 - DMwR

after_success:
  - Rscript -e 'library(covr);coveralls()'
