# .travis.yml
#
# https://docs.travis-ci.com/user/languages/r/

language: r
sudo: false
warnings_are_errors: false
cache: packages

r:
  - release

r_packages: 
  - covr
  - data.table
  - ggplot2
  - rARPACK
  - xgboost

before_install:
  - cd pkg/caret
 
after_success:
  - Rscript -e 'covr::codecov()'
