language: r
warnings_are_errors: false
sudo: required

env:
   global:
     - CRAN: http://cran.rstudio.com
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

install:
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo apt-get -qq update
  - ./travis-tool.sh aptget_install texlive-base
  - ./travis-tool.sh aptget_install biblatex
  - ./travis-tool.sh aptget_install texlive-latex-base
  - ./travis-tool.sh aptget_install texlive-latex-recommended
  - ./travis-tool.sh aptget_install texlive-latex-extra
  - ./travis-tool.sh aptget_install texlive-fonts-recommended
  - ./travis-tool.sh aptget_install texlive-fonts-extra
  - ./travis-tool.sh aptget_install texlive-science
  - ./travis-tool.sh github_package jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'
