# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
# http://docs.travis-ci.com/user/languages/r/

language: r
sudo: required
warnings_are_errors: true
r_build_args: "--no-build-vignettes --no-manual"
r_check_args: "--no-build-vignettes --no-manual --as-cran"

env:
   global:
     - CRAN: http://cran.rstudio.com"
   matrix:
     - NOT_CRAN="true"
     - NOT_CRAN="false"

before_script:
  - cd pkg/caret

r_packages:
  - ROSE
  - DMwR

r_binary_packages:
  - car
  - reshape2
  - foreach
  - plyr
  - nlme
  - BradleyTerry2
  - e1071
  - earth
  - fastICA
  - gam
  - ipred
  - kernlab
  - klaR
  - MASS
  - ellipse
  - mda
  - mgcv
  - mlbench
  - nnet
  - party
  - pls
  - pROC
  - proxy
  - randomForest
  - RANN
  - spls
  - subselect
  - pamr
  - superpc
  - Cubist
  - testthat
  - rARPACK
  - ggplot2
  - reshape2
  - data.table
  - caret

r_github_packages:
  - hadley/devtools
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);coveralls()'

after_failure:
  - Rscript -e 'devtools::load_all(); devtools::test()'
